//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmersmarket.service
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Results", Namespace = "http://schemas.datacontract.org/2004/07/farmersmarket.service")]
    public partial class Results : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private farmersmarket.service.Result[] resultsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public farmersmarket.service.Result[] results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Result", Namespace = "http://schemas.datacontract.org/2004/07/farmersmarket.service")]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idField;

        private string marketnameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string marketname
        {
            get
            {
                return this.marketnameField;
            }
            set
            {
                this.marketnameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "detailResult", Namespace = "http://schemas.datacontract.org/2004/07/farmersmarket.service")]
    public partial class detailResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private farmersmarket.service.marketdetails marketdetailsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public farmersmarket.service.marketdetails marketdetails
        {
            get
            {
                return this.marketdetailsField;
            }
            set
            {
                this.marketdetailsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "marketdetails", Namespace = "http://schemas.datacontract.org/2004/07/farmersmarket.service")]
    public partial class marketdetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AddressField;

        private string GoogleLinkField;

        private string ProductsField;

        private string ScheduleField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoogleLink
        {
            get
            {
                return this.GoogleLinkField;
            }
            set
            {
                this.GoogleLinkField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Schedule
        {
            get
            {
                return this.ScheduleField;
            }
            set
            {
                this.ScheduleField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IMarketService")]
public interface IMarketService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMarketService/zipSearch", ReplyAction = "http://tempuri.org/IMarketService/zipSearchResponse")]
    farmersmarket.service.Results zipSearch(string zip, string callback);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMarketService/locSearch", ReplyAction = "http://tempuri.org/IMarketService/locSearchResponse")]
    farmersmarket.service.Results locSearch(string lat, string lng, string callback);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IMarketService/mktDetail", ReplyAction = "http://tempuri.org/IMarketService/mktDetailResponse")]
    farmersmarket.service.detailResult mktDetail(string id, string callback);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMarketServiceChannel : IMarketService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MarketServiceClient : System.ServiceModel.ClientBase<IMarketService>, IMarketService
{

    public MarketServiceClient()
    {
    }

    public MarketServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public MarketServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public MarketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public MarketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public farmersmarket.service.Results zipSearch(string zip, string callback)
    {
        return base.Channel.zipSearch(zip, callback);
    }

    public farmersmarket.service.Results locSearch(string lat, string lng, string callback)
    {
        return base.Channel.locSearch(lat, lng, callback);
    }

    public farmersmarket.service.detailResult mktDetail(string id, string callback)
    {
        return base.Channel.mktDetail(id, callback);
    }
}
